[default.extend-words]

[files]
extend-exclude = [
    "CHANGELOG.md",
    "notebooks/*",
    "chat_server/fixtures/*",
    "chat_core/fixtures/*",
    "notify_server/fixtures/*",
    "notify_server/index.html",
]
