### signup user
POST http://127.0.0.1:6688/api/signup
Content-Type: application/json

{
    "workspace":"angularust",
    "email": "manonloki@gmail.com",
    "fullname":"Manon Loki",
    "password": "loki1988"
}



### signin user
# @name signin
POST http://127.0.0.1:6688/api/signin
Content-Type: application/json

{
    "email": "manonloki@gmail.com",
    "password": "loki1988"
}

@auth_token = {{signin.response.body.token}}

### get chat list
GET http://127.0.0.1:6688/api/chat
Authorization: Bearer {{auth_token}}

### get chat users list
GET http://127.0.0.1:6688/api/users
Authorization: Bearer {{auth_token}}

### upload files
POST http://127.0.0.1:6688/api/upload
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="avatar.png"
Content-Type: application/octet-stream

< /Users/manonloki/Documents/study/rust-camp/chat/avatar.png
--MyBoundary
Content-Disposition: form-data; filename="README.md"
Content-Type: text/plain

Hello World!

--MyBoundary--

### download files
GET http://127.0.0.1:6688/api/files/1/f75/640/ffdf8d0683cb49cccaf377073930af7904.png
Authorization: Bearer {{auth_token}}

### send message
POST http://127.0.0.1:6688/api/chats/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "content": "Hello World!",
    "files":[]
}

### get messages
GET http://127.0.0.1:6688/api/chats/1/messages
Authorization: Bearer {{auth_token}}
