server:
   port: 6688
   db_url: postgres://postgres:880914@localhost:5432/chat
auth:
   sk: |
      -----BEGIN PRIVATE KEY-----
      MC4CAQAwBQYDK2VwBCIEIDl3irF5y1+3vyCe4xib0qo3Iz1+9Oyu+HMaYiNiauXW
      -----END PRIVATE KEY-----
   pk: |
      -----BEGIN PUBLIC KEY-----
      MCowBQYDK2VwAyEAatkQHD1jJhkbQqax9MLk6423SbgVguvz0wk/fWPFDBY=
      -----END PUBLIC KEY-----
